spring:
  datasource:
    url: jdbc:mysql://kmerlink-database.cuuvxtvptbqs.us-east-1.rds.amazonaws.com:3306/gestion_de_stock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: kmerlinkAdmin
    password: kmerlinkdatabase18092022
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          #interceptor: fr.gestiondestock.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    #Open in view
    open-in-view: false

server:
  port: 8081

flickr:
  apiKey: 4722298ed15092cbb9764b9c848633bb
  apiSecret: 23dcaf5380c3657c
  appKey: 72157720819343603-af9fa137295cf939
  appSecret: 988f6967eeac3343
